const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const root = '/home/server/Projects/AutoPart-SyncDistributed/client';
function cart(storage) { const c={localStorage:storage}; vm.runInNewContext(fs.readFileSync(`${root}/js/cart.js`,'utf8')+';globalThis.result=Cart;',c); return c.result; }
test('cart persists normalized money and operations',()=>{let data={};const s={getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=v};let C=cart(s);assert.equal(C.addProduct({_id:'x',nome:'P',preco_venda:19.99}),true);C.addProduct({id:'x',nome:'P',preco_venda:19.99});C.setQuantity('x',3);assert.equal(C.total(),5997);C.remove('x');assert.deepEqual(Array.from(C.items()),[]);C.addProduct({id:'x',nome:'P',preco_venda:19.99});C.setQuantity('x',3);assert.equal(cart(s).total(),5997);});
test('cart recovers malformed storage and rejects invalid data',()=>{let data={'autopart.cart.v1':'bad'};const s={getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=v};let C=cart(s);assert.deepEqual(Array.from(C.items()),[]);assert.equal(C.addProduct({id:'',preco_venda:2}),false);assert.equal(C.addProduct({id:'x',preco_venda:'no'}),false);assert.equal(C.addProduct({id:'x',preco_venda:2}),true);assert.equal(C.setQuantity('x',0),false);});
test('api register and login use JSON without persisting passwords',async()=>{const calls=[];let data={};const ctx={localStorage:{getItem:k=>data[k]??null,setItem:(k,v)=>data[k]=v},fetch:async(url,opt)=>{calls.push([url,opt]);return {ok:true,headers:{get:()=> 'application/json'},json:async()=>({token:'t',user:{perfil:'cliente'}})}}};vm.runInNewContext(fs.readFileSync(`${root}/js/api.js`,'utf8')+';globalThis.api=api;',ctx);const registerResult=await ctx.api.register({nome:'N',email:'e',password:'secret'});const loginResult=await ctx.api.login({email:'e',password:'secret'});assert.equal(calls[0][0],'/api/auth/register');assert.equal(calls[1][0],'/api/auth/login');assert.equal(calls[0][1].method,'POST');assert.equal(calls[1][1].method,'POST');assert.equal(calls[0][1].headers['Content-Type'],'application/json');assert.equal(calls[1][1].headers['Content-Type'],'application/json');assert.deepEqual(JSON.parse(calls[0][1].body),{nome:'N',email:'e',password:'secret'});assert.deepEqual(JSON.parse(calls[1][1].body),{email:'e',password:'secret'});assert.equal(JSON.stringify(registerResult).includes('password'),false);assert.equal(JSON.stringify(registerResult).includes('senha'),false);assert.equal(JSON.stringify(loginResult).includes('password'),false);assert.equal(JSON.stringify(loginResult).includes('senha'),false);assert.equal(Object.values(data).join(' ').includes('secret'),false);});
test('app contains required customer surfaces and no checkout mutations',()=>{const s=fs.readFileSync(`${root}/js/app.js`,'utf8');for(const x of ['api.register','type="password"','perfil === \'cliente\'','pageCart','Cart.addProduct','Valide nome'])assert.ok(s.includes(x),x);assert.ok(s.includes('api.checkout(Cart.items())'));assert.ok(s.includes('pageOrders'));assert.ok(s.includes('Meus pedidos'));});
