const mongoose=require('mongoose');const Peca=require('../models/Part');const Order=require('../models/Order');
const safe=o=>({id:String(o._id),items:o.items.map(i=>({partId:String(i.partId),partCode:i.partCode,partName:i.partName,unitPrice:i.unitPrice,quantity:i.quantity})),total:o.total,status:o.status,criado_em:o.criado_em});const fail=(r,s,m)=>r.status(s).json({erro:true,codigo:s,mensagem:m});
class OrdersController{
 static async checkout(req,res){const b=req.body;if(!b||!Array.isArray(b.items)||!b.items.length||Object.keys(b).length!==1)return fail(res,400,'Payload inválido');const seen=new Set(),items=[];for(const i of b.items){if(!i||Object.keys(i).sort().join(',')!=='partId,quantity'||typeof i.partId!=='string'||!mongoose.Types.ObjectId.isValid(i.partId)||seen.has(i.partId)||!Number.isSafeInteger(i.quantity)||i.quantity<=0)return fail(res,400,'Item inválido');seen.add(i.partId);items.push({partId:new mongoose.Types.ObjectId(i.partId),quantity:i.quantity});}const session=await mongoose.startSession();try{let created;await session.withTransaction(async()=>{const parts=await Peca.find({_id:{$in:items.map(i=>i.partId)},ativo:true}).session(session);if(parts.length!==items.length){const e=new Error('Peça não encontrada');e.status=404;throw e;}const map=new Map(parts.map(p=>[String(p._id),p]));if(items.some(i=>!map.has(String(i.partId)))){const e=new Error('Peça não encontrada');e.status=404;throw e;}if(items.some(i=>map.get(String(i.partId)).estoque_atual<i.quantity)){const e=new Error('Estoque insuficiente');e.status=409;throw e;}const snapshots=items.map(i=>{const p=map.get(String(i.partId));return{partId:p._id,partCode:p.codigo,partName:p.nome,unitPrice:p.preco_venda,quantity:i.quantity};});[created]=await Order.create([{customerId:req.user.id,items:snapshots,total:snapshots.reduce((s,i)=>s+i.unitPrice*i.quantity,0),status:'pendente'}],{session});for(const i of items){const x=await Peca.updateOne({_id:i.partId,ativo:true,estoque_atual:{$gte:i.quantity}},{$inc:{estoque_atual:-i.quantity}},{session});if(x.modifiedCount!==1){const e=new Error('Conflito de estoque');e.status=409;throw e;}}});res.status(201).json(safe(created));}catch(e){fail(res,e.status||(e.name==='ValidationError'?400:500),e.status?e.message:'Não foi possível finalizar o pedido');}finally{await session.endSession();}}
 static async me(req,res){res.json((await Order.find({customerId:req.user.id}).sort({criado_em:-1})).map(safe));}
 static async detail(req,res){if(!mongoose.Types.ObjectId.isValid(req.params.id))return fail(res,404,'Pedido não encontrado');const o=await Order.findOne({_id:req.params.id,customerId:req.user.id});if(!o)return fail(res,404,'Pedido não encontrado');res.json(safe(o));}
 static adminProjection(o){return{id:String(o._id),customer:o.customerId&&{id:String(o.customerId._id),nome:o.customerId.nome,email:o.customerId.email},items:o.items.map(i=>({partId:String(i.partId),partCode:i.partCode,partName:i.partName,unitPrice:i.unitPrice,quantity:i.quantity})),total:o.total,status:o.status,criado_em:o.criado_em};}
 static async adminList(req,res){const os=await Order.find({}).populate('customerId','nome email').sort({criado_em:-1});res.json(os.map(o=>OrdersController.adminProjection(o)));}
 static async adminDetail(req,res){if(!mongoose.Types.ObjectId.isValid(req.params.id))return fail(res,404,'Pedido não encontrado');const o=await Order.findById(req.params.id).populate('customerId','nome email');if(!o)return fail(res,404,'Pedido não encontrado');res.json(OrdersController.adminProjection(o));}
 static async adminUpdateStatus(req,res){if(!req.body||Object.keys(req.body).length!==1||typeof req.body.status!=='string')return fail(res,400,'Status inválido');const o=await Order.findById(req.params.id);if(!o)return fail(res,404,'Pedido não encontrado');const next={pendente:['confirmado','cancelado'],confirmado:['em_processamento','cancelado'],em_processamento:['enviado','cancelado'],enviado:['concluido'],concluido:[],cancelado:[]};if(!Object.values(next).flat().includes(req.body.status))return fail(res,400,'Status inválido');if(!next[o.status].includes(req.body.status))return fail(res,409,'Transição de status não permitida');o.status=req.body.status;await o.save();const full=await o.populate('customerId','nome email');res.json(OrdersController.adminProjection(full));}
}module.exports=OrdersController;
