const test = require('node:test');
const assert = require('node:assert/strict');
process.env.NODE_ENV = 'test';
process.env.MONGODB_URI = 'mongodb://127.0.0.1:27018/autopart_fase1_test';
const mongoose = require('mongoose');
const bcrypt = require('bcryptjs');
const { connect, close } = require('../src/config/db');
const { createApp } = require('../src/app');
const User = require('../src/models/User');
const Part = require('../src/models/Part');
const Order = require('../src/models/Order');
let server, base, a, b, admin, p1, p2;
async function request(path, options={}) { const r=await fetch(base+path,{headers:{'content-type':'application/json',...(options.token?{authorization:`Bearer ${options.token}`}:{})},...options,body:options.body&&JSON.stringify(options.body)}); return {status:r.status,body:await r.json()}; }
async function login(email,password='password123') { return (await request('/api/auth/login',{method:'POST',body:{email,password}})).body.token; }
test.before(async()=>{ await connect(); await mongoose.connection.dropDatabase(); server=createApp().listen(0); await new Promise(r=>server.once('listening',r)); base=`http://127.0.0.1:${server.address().port}`; a=(await request('/api/auth/register',{method:'POST',body:{nome:'A',email:'a@test.local',password:'password123'}})).body.user; b=(await request('/api/auth/register',{method:'POST',body:{nome:'B',email:'b@test.local',password:'password123'}})).body.user; admin=await User.create({nome:'Admin',email:'admin@test.local',senha:await bcrypt.hash('password123',10),perfil:'admin'}); p1=await Part.create({codigo:'F4-A',nome:'Pastilha real',preco_custo:10,preco_venda:25,estoque_atual:3,compatibilidades:[{marca:'Ford',modelo:'Ka',anos:[2020]}]}); p2=await Part.create({codigo:'F4-B',nome:'Filtro real',preco_custo:5,preco_venda:12,estoque_atual:2,compatibilidades:[{marca:'VW',modelo:'Gol',anos:[2021]}]});});
test.after(async()=>{ await mongoose.connection.dropDatabase(); await new Promise(r=>server.close(r)); await close(); });
test('checkout enforces narrow authoritative contract and access control',async()=>{const at=await login('a@test.local'); let r=await request('/api/orders/checkout',{method:'POST',token:at,body:{items:[{partId:String(p1._id),quantity:1,name:'forged',price:0,unitPrice:0,total:0,status:'cancelado'}],customerId:'forged'}}); assert.equal(r.status,400); r=await request('/api/orders/checkout',{method:'POST',token:at,body:{items:[{partId:String(p1._id),quantity:1}]}}); assert.equal(r.status,201); assert.equal(r.body.items[0].partName,'Pastilha real'); assert.equal(r.body.total,25); assert.equal(r.body.status,'pendente'); assert.equal(String(r.body.customerId),'undefined'); assert.equal((await request('/api/orders/checkout',{method:'POST',body:{items:[{partId:String(p1._id),quantity:1}]}})).status,401); assert.equal((await request('/api/orders/checkout',{method:'POST',token:await login('admin@test.local'),body:{items:[{partId:String(p1._id),quantity:1}]}})).status,403);});
test('insufficient cart is atomic and successful cart decrements once',async()=>{const at=await login('a@test.local'), before=await Order.countDocuments(), stocks=await Part.find({_id:{$in:[p1._id,p2._id]}}); let r=await request('/api/orders/checkout',{method:'POST',token:at,body:{items:[{partId:String(p1._id),quantity:99},{partId:String(p2._id),quantity:1}]}}); assert.equal(r.status,409); assert.equal(await Order.countDocuments(),before); let after=await Part.find({_id:{$in:[p1._id,p2._id]}}); assert.deepEqual(after.map(x=>x.estoque_atual).sort(),stocks.map(x=>x.estoque_atual).sort()); r=await request('/api/orders/checkout',{method:'POST',token:at,body:{items:[{partId:String(p1._id),quantity:1},{partId:String(p2._id),quantity:2}]}}); assert.equal(r.status,201); assert.equal(await Order.countDocuments(),before+1); after=await Part.find({_id:{$in:[p1._id,p2._id]}}); assert.deepEqual(after.map(x=>x.estoque_atual).sort(),[0,1]);});
test('orders persist and are customer scoped',async()=>{const order=await Order.findOne().sort({criado_em:-1}), at=await login('a@test.local'), bt=await login('b@test.local'); await close(); await connect(); assert.ok(await Order.findById(order._id)); assert.equal((await request('/api/orders/me',{token:at})).body.length,2); assert.equal((await request(`/api/orders/${order._id}`,{token:bt})).status,404);});
